TWENTY_ACTIONS = [{'name': 'action_1', 'cost': 20, 'income': 5},
                  {'name': 'action_2', 'cost': 30, 'income': 10},
                  {'name': 'action_3', 'cost': 50, 'income': 15},
                  {'name': 'action_4', 'cost': 70, 'income': 20},
                  {'name': 'action_5', 'cost': 60, 'income': 17},
                  {'name': 'action_6', 'cost': 80, 'income': 25},
                  {'name': 'action_7', 'cost': 22, 'income': 7},
                  {'name': 'action_8', 'cost': 26, 'income': 11},
                  {'name': 'action_9', 'cost': 48, 'income': 13},
                  {'name': 'action_10', 'cost': 34, 'income': 27},
                  {'name': 'action_11', 'cost': 42, 'income': 17},
                  {'name': 'action_12', 'cost': 110, 'income': 9},
                  {'name': 'action_13', 'cost': 38, 'income': 23},
                  {'name': 'action_14', 'cost': 14, 'income': 1},
                  {'name': 'action_15', 'cost': 18, 'income': 3},
                  {'name': 'action_16', 'cost': 8, 'income': 8},
                  {'name': 'action_17', 'cost': 4, 'income': 12},
                  {'name': 'action_18', 'cost': 10, 'income': 14},
                  {'name': 'action_19', 'cost': 24, 'income': 21},
                  {'name': 'action_20', 'cost': 114, 'income': 18}]

FOOR_ACTIONS = [{'name': 'action_1', 'cost': 20, 'income': 5},
                {'name': 'action_2', 'cost': 30, 'income': 10},
                {'name': 'action_3', 'cost': 50, 'income': 15},
                {'name': 'action_4', 'cost': 70, 'income': 20}]
